name: gpu
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta_gpu_build_horovod
        uses: docker/metadata-action@v4
        with:
          images: |
            tencentailab/hok_env
          flavor: |
            prefix=gpu_build_horovod
          tags: |
            type=semver,pattern={{raw}}
            type=sha,prefix=gpu_build_horovod_
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_gpu_build_horovod.outputs.tags }}
          labels: ${{ steps.meta_gpu_build_horovod.outputs.labels }}
          file: dockerfile/dockerfile.base.gpu
          cache-from: type=registry,ref=tencentailab/hok_env:buildcache_gpu_build_horovod
          cache-to: type=registry,ref=tencentailab/hok_env:buildcache_gpu_build_horovod,mode=max
          target: build_horovod
          build-args: |
            BASE_IMAGE=tencentailab/hok_env:base_common_py38_base_v1.2.0
            BUILD_PYTHON_IMAGE=tencentailab/hok_env:base_build_python38_base_v1.2.0
      -
        name: Docker meta
        id: meta_gpu_base
        uses: docker/metadata-action@v4
        with:
          images: |
            tencentailab/hok_env
          flavor: |
            prefix=gpu_base_
          tags: |
            type=semver,pattern={{raw}}
            type=sha,prefix=gpu_base_
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_gpu_base.outputs.tags }}
          labels: ${{ steps.meta_gpu_base.outputs.labels }}
          file: dockerfile/dockerfile.base.gpu
          cache-from: type=registry,ref=tencentailab/hok_env:buildcache_gpu_base
          cache-to: type=registry,ref=tencentailab/hok_env:buildcache_gpu_base,mode=max
          build-args: |
            BASE_IMAGE=tencentailab/hok_env:base_common_py38_base_v1.2.0
            BUILD_PYTHON_IMAGE=tencentailab/hok_env:base_build_python38_base_v1.2.0
      -
        name: Docker meta
        id: meta_gpu
        uses: docker/metadata-action@v4
        with:
          images: |
            tencentailab/hok_env
          flavor: |
            prefix=gpu_
          tags: |
            type=semver,pattern={{raw}}
            type=sha,prefix=gpu_
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_gpu.outputs.tags }}
          labels: ${{ steps.meta_gpu.outputs.labels }}
          file: dockerfile/dockerfile.dev
          cache-from: type=registry,ref=tencentailab/hok_env:buildcache_gpu
          cache-to: type=registry,ref=tencentailab/hok_env:buildcache_gpu,mode=max
          build-args: |
            BASE_IMAGE=tencentailab/hok_env:gpu_base_v1.2.0
      -
        name: Docker meta 3v3
        id: meta_gpu_3v3
        uses: docker/metadata-action@v4
        with:
          images: |
            tencentailab/hok_env
          flavor: |
            prefix=gpu_3v3_
          tags: |
            type=semver,pattern={{raw}}
            type=sha,prefix=gpu_3v3_
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_gpu.outputs.tags }}
          labels: ${{ steps.meta_gpu.outputs.labels }}
          file: dockerfile/dockerfile.dev.3v3
          cache-from: type=registry,ref=tencentailab/hok_env:buildcache_gpu_3v3
          cache-to: type=registry,ref=tencentailab/hok_env:buildcache_gpu_3v3,mode=max
          build-args: |
            BASE_IMAGE=tencentailab/hok_env:gpu_base_v1.2.0
